title: BS Title
author: Borto
email: borto@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I don't know what the commented out line above this one means :o

# social links
twitter_username: I don't know that is a handle # DO NOT include the @ character, or else the build will fail!
github_username:  still don't know :o # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
